// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { ActivityInboxPage } from "~/components/registry/workflows-onboarding/activity-inbox-page";
import { registryItemBySlug } from "~/lib/registry";

export default function ActivityInboxPagePage() {
  return (
    <>
      <Title>ActivityInboxPage | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["activity-inbox-page"]}>
        <ActivityInboxPage />
      </RegistryPageShell>
    </>
  );
}
