// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { AnalyticsOverview } from "~/components/registry/app-shells-dashboards/analytics-overview";
import { registryItemBySlug } from "~/lib/registry";

export default function AnalyticsOverviewPage() {
  return (
    <>
      <Title>AnalyticsOverview | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["analytics-overview"]}>
        <AnalyticsOverview />
      </RegistryPageShell>
    </>
  );
}
