// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { APIKeysPage } from "~/components/registry/settings-admin/api-keys-page";
import { registryItemBySlug } from "~/lib/registry";

export default function APIKeysPagePage() {
  return (
    <>
      <Title>APIKeysPage | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["api-keys-page"]}>
        <APIKeysPage />
      </RegistryPageShell>
    </>
  );
}
