// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { AuditLogPage } from "~/components/registry/settings-admin/audit-log-page";
import { registryItemBySlug } from "~/lib/registry";

export default function AuditLogPagePage() {
  return (
    <>
      <Title>AuditLogPage | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["audit-log-page"]}>
        <AuditLogPage />
      </RegistryPageShell>
    </>
  );
}
