// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { BillingSettings } from "~/components/registry/settings-admin/billing-settings";
import { registryItemBySlug } from "~/lib/registry";

export default function BillingSettingsPage() {
  return (
    <>
      <Title>BillingSettings | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["billing-settings"]}>
        <BillingSettings />
      </RegistryPageShell>
    </>
  );
}
