// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { CareersListing } from "~/components/registry/trust-company/careers-listing";
import { registryItemBySlug } from "~/lib/registry";

export default function CareersListingPage() {
  return (
    <>
      <Title>CareersListing | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["careers-listing"]}>
        <CareersListing />
      </RegistryPageShell>
    </>
  );
}
