// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { ChangelogTimelinePage } from "~/components/registry/docs-editorial/changelog-timeline-page";
import { registryItemBySlug } from "~/lib/registry";

export default function ChangelogTimelinePagePage() {
  return (
    <>
      <Title>ChangelogTimelinePage | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["changelog-timeline-page"]}>
        <ChangelogTimelinePage />
      </RegistryPageShell>
    </>
  );
}
