// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { CreateProjectFlow } from "~/components/registry/workflows-onboarding/create-project-flow";
import { registryItemBySlug } from "~/lib/registry";

export default function CreateProjectFlowPage() {
  return (
    <>
      <Title>CreateProjectFlow | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["create-project-flow"]}>
        <CreateProjectFlow />
      </RegistryPageShell>
    </>
  );
}
