// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { CRMWorkspace } from "~/components/registry/app-shells-dashboards/crm-workspace";
import { registryItemBySlug } from "~/lib/registry";

export default function CRMWorkspacePage() {
  return (
    <>
      <Title>CRMWorkspace | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["crm-workspace"]}>
        <CRMWorkspace />
      </RegistryPageShell>
    </>
  );
}
