// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { DashboardSidebarSimple } from "~/components/registry/app-shells-dashboards/dashboard-sidebar-simple";
import { registryItemBySlug } from "~/lib/registry";

export default function DashboardSidebarSimplePage() {
  return (
    <>
      <Title>DashboardSidebarSimple | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["dashboard-sidebar-simple"]}>
        <DashboardSidebarSimple />
      </RegistryPageShell>
    </>
  );
}
