// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { DashboardTopbarOnly } from "~/components/registry/app-shells-dashboards/dashboard-topbar-only";
import { registryItemBySlug } from "~/lib/registry";

export default function DashboardTopbarOnlyPage() {
  return (
    <>
      <Title>DashboardTopbarOnly | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["dashboard-topbar-only"]}>
        <DashboardTopbarOnly />
      </RegistryPageShell>
    </>
  );
}
