// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { DashboardSidebarCollapsible } from "~/components/registry/app-shells-dashboards/dashboard-sidebar-collapsible";
import { registryItemBySlug } from "~/lib/registry";

export default function DashboardSidebarCollapsiblePage() {
  return (
    <>
      <Title>DashboardSidebarCollapsible | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["dashboard-sidebar-collapsible"]}>
        <DashboardSidebarCollapsible />
      </RegistryPageShell>
    </>
  );
}
