// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { DocsSidebarLayout } from "~/components/registry/docs-editorial/docs-sidebar-layout";
import { registryItemBySlug } from "~/lib/registry";

export default function DocsSidebarLayoutPage() {
  return (
    <>
      <Title>DocsSidebarLayout | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["docs-sidebar-layout"]}>
        <DocsSidebarLayout />
      </RegistryPageShell>
    </>
  );
}
