// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { EmptyWorkspace } from "~/components/registry/workflows-onboarding/empty-workspace";
import { registryItemBySlug } from "~/lib/registry";

export default function EmptyWorkspacePage() {
  return (
    <>
      <Title>EmptyWorkspace | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["empty-workspace"]}>
        <EmptyWorkspace />
      </RegistryPageShell>
    </>
  );
}
