// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { ForgotPassword } from "~/components/registry/authentication/forgot-password";
import { registryItemBySlug } from "~/lib/registry";

export default function ForgotPasswordPage() {
  return (
    <>
      <Title>ForgotPassword | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["forgot-password"]}>
        <ForgotPassword />
      </RegistryPageShell>
    </>
  );
}
