// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { ImportDataWizard } from "~/components/registry/workflows-onboarding/import-data-wizard";
import { registryItemBySlug } from "~/lib/registry";

export default function ImportDataWizardPage() {
  return (
    <>
      <Title>ImportDataWizard | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["import-data-wizard"]}>
        <ImportDataWizard />
      </RegistryPageShell>
    </>
  );
}
