// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { LoginBasic } from "~/components/registry/authentication/login-basic";
import { registryItemBySlug } from "~/lib/registry";

export default function LoginBasicPage() {
  return (
    <>
      <Title>LoginBasic | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["login-basic"]}>
        <LoginBasic />
      </RegistryPageShell>
    </>
  );
}
