// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { LoginSplit } from "~/components/registry/authentication/login-split";
import { registryItemBySlug } from "~/lib/registry";

export default function LoginSplitPage() {
  return (
    <>
      <Title>LoginSplit | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["login-split"]}>
        <LoginSplit />
      </RegistryPageShell>
    </>
  );
}
