// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { LoginMagicLink } from "~/components/registry/authentication/login-magic-link";
import { registryItemBySlug } from "~/lib/registry";

export default function LoginMagicLinkPage() {
  return (
    <>
      <Title>LoginMagicLink | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["login-magic-link"]}>
        <LoginMagicLink />
      </RegistryPageShell>
    </>
  );
}
