// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { MembersDirectory } from "~/components/registry/app-shells-dashboards/members-directory";
import { registryItemBySlug } from "~/lib/registry";

export default function MembersDirectoryPage() {
  return (
    <>
      <Title>MembersDirectory | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["members-directory"]}>
        <MembersDirectory />
      </RegistryPageShell>
    </>
  );
}
