// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { NotificationSettings } from "~/components/registry/settings-admin/notification-settings";
import { registryItemBySlug } from "~/lib/registry";

export default function NotificationSettingsPage() {
  return (
    <>
      <Title>NotificationSettings | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["notification-settings"]}>
        <NotificationSettings />
      </RegistryPageShell>
    </>
  );
}
