// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { OTPVerify } from "~/components/registry/authentication/otp-verify";
import { registryItemBySlug } from "~/lib/registry";

export default function OTPVerifyPage() {
  return (
    <>
      <Title>OTPVerify | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["otp-verify"]}>
        <OTPVerify />
      </RegistryPageShell>
    </>
  );
}
