// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { ProfileSettings } from "~/components/registry/settings-admin/profile-settings";
import { registryItemBySlug } from "~/lib/registry";

export default function ProfileSettingsPage() {
  return (
    <>
      <Title>ProfileSettings | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["profile-settings"]}>
        <ProfileSettings />
      </RegistryPageShell>
    </>
  );
}
