// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { ProjectsDashboard } from "~/components/registry/app-shells-dashboards/projects-dashboard";
import { registryItemBySlug } from "~/lib/registry";

export default function ProjectsDashboardPage() {
  return (
    <>
      <Title>ProjectsDashboard | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["projects-dashboard"]}>
        <ProjectsDashboard />
      </RegistryPageShell>
    </>
  );
}
