// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { ResetPassword } from "~/components/registry/authentication/reset-password";
import { registryItemBySlug } from "~/lib/registry";

export default function ResetPasswordPage() {
  return (
    <>
      <Title>ResetPassword | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["reset-password"]}>
        <ResetPassword />
      </RegistryPageShell>
    </>
  );
}
