// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { RevenueDashboard } from "~/components/registry/app-shells-dashboards/revenue-dashboard";
import { registryItemBySlug } from "~/lib/registry";

export default function RevenueDashboardPage() {
  return (
    <>
      <Title>RevenueDashboard | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["revenue-dashboard"]}>
        <RevenueDashboard />
      </RegistryPageShell>
    </>
  );
}
