// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { SecuritySettings } from "~/components/registry/settings-admin/security-settings";
import { registryItemBySlug } from "~/lib/registry";

export default function SecuritySettingsPage() {
  return (
    <>
      <Title>SecuritySettings | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["security-settings"]}>
        <SecuritySettings />
      </RegistryPageShell>
    </>
  );
}
