// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { SignupInvite } from "~/components/registry/authentication/signup-invite";
import { registryItemBySlug } from "~/lib/registry";

export default function SignupInvitePage() {
  return (
    <>
      <Title>SignupInvite | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["signup-invite"]}>
        <SignupInvite />
      </RegistryPageShell>
    </>
  );
}
