// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { SignupBasic } from "~/components/registry/authentication/signup-basic";
import { registryItemBySlug } from "~/lib/registry";

export default function SignupBasicPage() {
  return (
    <>
      <Title>SignupBasic | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["signup-basic"]}>
        <SignupBasic />
      </RegistryPageShell>
    </>
  );
}
