// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { SignupWorkspace } from "~/components/registry/authentication/signup-workspace";
import { registryItemBySlug } from "~/lib/registry";

export default function SignupWorkspacePage() {
  return (
    <>
      <Title>SignupWorkspace | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["signup-workspace"]}>
        <SignupWorkspace />
      </RegistryPageShell>
    </>
  );
}
