// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { StatusPageSummary } from "~/components/registry/trust-company/status-page-summary";
import { registryItemBySlug } from "~/lib/registry";

export default function StatusPageSummaryPage() {
  return (
    <>
      <Title>StatusPageSummary | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["status-page-summary"]}>
        <StatusPageSummary />
      </RegistryPageShell>
    </>
  );
}
