// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { SupportInbox } from "~/components/registry/app-shells-dashboards/support-inbox";
import { registryItemBySlug } from "~/lib/registry";

export default function SupportInboxPage() {
  return (
    <>
      <Title>SupportInbox | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["support-inbox"]}>
        <SupportInbox />
      </RegistryPageShell>
    </>
  );
}
