// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { TeamSettings } from "~/components/registry/settings-admin/team-settings";
import { registryItemBySlug } from "~/lib/registry";

export default function TeamSettingsPage() {
  return (
    <>
      <Title>TeamSettings | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["team-settings"]}>
        <TeamSettings />
      </RegistryPageShell>
    </>
  );
}
