// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { TwoFactorSetup } from "~/components/registry/authentication/two-factor-setup";
import { registryItemBySlug } from "~/lib/registry";

export default function TwoFactorSetupPage() {
  return (
    <>
      <Title>TwoFactorSetup | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["two-factor-setup"]}>
        <TwoFactorSetup />
      </RegistryPageShell>
    </>
  );
}
