// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { TwoFactorChallenge } from "~/components/registry/authentication/two-factor-challenge";
import { registryItemBySlug } from "~/lib/registry";

export default function TwoFactorChallengePage() {
  return (
    <>
      <Title>TwoFactorChallenge | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["two-factor-challenge"]}>
        <TwoFactorChallenge />
      </RegistryPageShell>
    </>
  );
}
