// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { VerifyEmail } from "~/components/registry/authentication/verify-email";
import { registryItemBySlug } from "~/lib/registry";

export default function VerifyEmailPage() {
  return (
    <>
      <Title>VerifyEmail | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["verify-email"]}>
        <VerifyEmail />
      </RegistryPageShell>
    </>
  );
}
