export function renderGeneratedStorageModule() {
  return [
    'import { DeleteObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";',
    'import { getSignedUrl } from "@aws-sdk/s3-request-presigner";',
    'import { env } from "~/lib/env";',
    "",
    "export type UploadIntent = {",
    "  key: string;",
    "  contentType: string;",
    "  expiresIn?: number;",
    "};",
    "",
    "function parseForcePathStyle(value?: string) {",
    '  return value === "true" || value === "1";',
    "}",
    "",
    "function storageRegion() {",
    '  return env.AWS_REGION ?? env.S3_REGION ?? "us-east-1";',
    "}",
    "",
    "function storageEndpoint() {",
    "  return env.AWS_ENDPOINT_URL_S3 || env.S3_ENDPOINT || undefined;",
    "}",
    "",
    "function storageAccessKeyId() {",
    "  const value = env.AWS_ACCESS_KEY_ID || env.S3_ACCESS_KEY_ID;",
    '  if (!value) throw new Error("Missing object storage access key. Set AWS_ACCESS_KEY_ID or S3_ACCESS_KEY_ID.");',
    "  return value;",
    "}",
    "",
    "function storageSecretAccessKey() {",
    "  const value = env.AWS_SECRET_ACCESS_KEY || env.S3_SECRET_ACCESS_KEY;",
    '  if (!value) throw new Error("Missing object storage secret key. Set AWS_SECRET_ACCESS_KEY or S3_SECRET_ACCESS_KEY.");',
    "  return value;",
    "}",
    "",
    "export function getStorageClient() {",
    "  return new S3Client({",
    "    region: storageRegion(),",
    "    bucketEndpoint: false,",
    "    endpoint: storageEndpoint(),",
    '    requestChecksumCalculation: "WHEN_REQUIRED",',
    '    responseChecksumValidation: "WHEN_REQUIRED",',
    "    forcePathStyle: parseForcePathStyle(env.S3_FORCE_PATH_STYLE),",
    "    credentials: {",
    "      accessKeyId: storageAccessKeyId(),",
    "      secretAccessKey: storageSecretAccessKey(),",
    "    },",
    "  });",
    "}",
    "",
    "export async function createPresignedUpload(input: UploadIntent) {",
    "  const client = getStorageClient();",
    "  const expiresIn = input.expiresIn ?? 900;",
    "  const command = new PutObjectCommand({",
    "    Bucket: env.S3_BUCKET,",
    "    Key: input.key,",
    "    ContentType: input.contentType,",
    "  });",
    "  const url = await getSignedUrl(client, command, { expiresIn });",
    "  return {",
    "    method: 'PUT' as const,",
    "    url,",
    "    key: input.key,",
    "    bucket: env.S3_BUCKET,",
    "    expiresIn,",
    "    headers: {",
    '      "content-type": input.contentType,',
    "    },",
    "  };",
    "}",
    "",
    "export async function deleteObject(key: string) {",
    "  const client = getStorageClient();",
    "  await client.send(",
    "    new DeleteObjectCommand({",
    "      Bucket: env.S3_BUCKET,",
    "      Key: key,",
    "    }),",
    "  );",
    "}",
    "",
    "export function buildObjectUrl(key: string) {",
    "  if (env.S3_PUBLIC_BASE_URL) {",
    "    return new URL(key, env.S3_PUBLIC_BASE_URL.endsWith('/') ? env.S3_PUBLIC_BASE_URL : `${env.S3_PUBLIC_BASE_URL}/`).toString();",
    "  }",
    "",
    "  const endpoint = storageEndpoint();",
    "  if (endpoint) {",
    "    const url = new URL(endpoint);",
    "    if (parseForcePathStyle(env.S3_FORCE_PATH_STYLE)) {",
    "      return new URL(`${env.S3_BUCKET}/${key}`, url.toString().endsWith('/') ? url.toString() : `${url.toString()}/`).toString();",
    "    }",
    "    return `${url.protocol}//${env.S3_BUCKET}.${url.host}/${key}`;",
    "  }",
    "",
    "  return `https://${env.S3_BUCKET}.s3.${storageRegion()}.amazonaws.com/${key}`;",
    "}",
    "",
  ].join("\n");
}
