import type { AppIR } from "../../compiler/generated-app.js";

export function renderGeneratedStorageModule(app: AppIR) {
  const policy = {
    maxFileSizeBytes: app.storage?.maxFileSizeBytes ?? 25 * 1024 * 1024,
    allowedContentTypes: app.storage?.allowedContentTypes ?? [],
    keyPrefix: app.storage?.keyPrefix ?? "uploads",
    presignExpiresSeconds: app.storage?.presignExpiresSeconds ?? 900,
    objectPolicy: app.storage?.objectPolicy ?? "private",
    deleteMode: app.storage?.deleteMode ?? "hard",
  };

  return [
    'import { DeleteObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";',
    'import { getSignedUrl } from "@aws-sdk/s3-request-presigner";',
    'import { env } from "~/lib/env";',
    "",
    "export type UploadIntent = {",
    "  key: string;",
    "  contentType: string;",
    "  fileSize?: number;",
    "  expiresIn?: number;",
    "};",
    "",
    `export const storagePolicy = ${JSON.stringify(policy, null, 2)} as const;`,
    "",
    "function assertUploadAllowed(input: UploadIntent) {",
    "  if (input.fileSize !== undefined && input.fileSize > storagePolicy.maxFileSizeBytes) {",
    "    throw new Error(`File exceeds max upload size of ${storagePolicy.maxFileSizeBytes} bytes.`);",
    "  }",
    "  if (storagePolicy.allowedContentTypes.length > 0 && !(storagePolicy.allowedContentTypes as readonly string[]).includes(input.contentType)) {",
    "    throw new Error(`Content type ${input.contentType} is not allowed by storage policy.`);",
    "  }",
    "  if (!input.key.startsWith(`${storagePolicy.keyPrefix}/`)) {",
    "    throw new Error(`Object key must start with ${storagePolicy.keyPrefix}/.`);",
    "  }",
    "}",
    "",
    "function parseForcePathStyle(value?: string) {",
    '  return value === "true" || value === "1";',
    "}",
    "",
    "function storageRegion() {",
    '  return env.AWS_REGION ?? env.S3_REGION ?? "us-east-1";',
    "}",
    "",
    "function storageBucket() {",
    "  const value = env.AWS_S3_BUCKET || env.S3_BUCKET;",
    '  if (!value) throw new Error("Missing object storage bucket. Set AWS_S3_BUCKET or S3_BUCKET.");',
    "  return value;",
    "}",
    "",
    "function storageEndpoint() {",
    "  return env.AWS_ENDPOINT_URL_S3 || env.S3_ENDPOINT || undefined;",
    "}",
    "",
    "function storageAccessKeyId() {",
    "  const value = env.AWS_ACCESS_KEY_ID || env.S3_ACCESS_KEY_ID;",
    '  if (!value) throw new Error("Missing object storage access key. Set AWS_ACCESS_KEY_ID or S3_ACCESS_KEY_ID.");',
    "  return value;",
    "}",
    "",
    "function storageSecretAccessKey() {",
    "  const value = env.AWS_SECRET_ACCESS_KEY || env.S3_SECRET_ACCESS_KEY;",
    '  if (!value) throw new Error("Missing object storage secret key. Set AWS_SECRET_ACCESS_KEY or S3_SECRET_ACCESS_KEY.");',
    "  return value;",
    "}",
    "",
    "export function getStorageClient() {",
    "  return new S3Client({",
    "    region: storageRegion(),",
    "    bucketEndpoint: false,",
    "    endpoint: storageEndpoint(),",
    '    requestChecksumCalculation: "WHEN_REQUIRED",',
    '    responseChecksumValidation: "WHEN_REQUIRED",',
    "    forcePathStyle: parseForcePathStyle(env.S3_FORCE_PATH_STYLE),",
    "    credentials: {",
    "      accessKeyId: storageAccessKeyId(),",
    "      secretAccessKey: storageSecretAccessKey(),",
    "    },",
    "  });",
    "}",
    "",
    "export async function createPresignedUpload(input: UploadIntent) {",
    "  assertUploadAllowed(input);",
    "  const client = getStorageClient();",
    "  const expiresIn = input.expiresIn ?? storagePolicy.presignExpiresSeconds;",
    "  const command = new PutObjectCommand({",
    "    Bucket: storageBucket(),",
    "    Key: input.key,",
    "    ContentType: input.contentType,",
    "  });",
    "  const url = await getSignedUrl(client, command, { expiresIn });",
    "  return {",
    "    method: 'PUT' as const,",
    "    url,",
    "    key: input.key,",
    "    bucket: storageBucket(),",
    "    expiresIn,",
    "    policy: storagePolicy,",
    "    headers: {",
    '      "content-type": input.contentType,',
    "    },",
    "  };",
    "}",
    "",
    "export async function deleteObject(key: string) {",
    "  const client = getStorageClient();",
    "  await client.send(",
    "    new DeleteObjectCommand({",
    "      Bucket: storageBucket(),",
    "      Key: key,",
    "    }),",
    "  );",
    "}",
    "",
    "export function buildObjectUrl(key: string) {",
    "  if (env.S3_PUBLIC_BASE_URL) {",
    "    return new URL(key, env.S3_PUBLIC_BASE_URL.endsWith('/') ? env.S3_PUBLIC_BASE_URL : `${env.S3_PUBLIC_BASE_URL}/`).toString();",
    "  }",
    "",
    "  const endpoint = storageEndpoint();",
    "  if (endpoint) {",
    "    const url = new URL(endpoint);",
    "    if (parseForcePathStyle(env.S3_FORCE_PATH_STYLE)) {",
    "      return new URL(`${storageBucket()}/${key}`, url.toString().endsWith('/') ? url.toString() : `${url.toString()}/`).toString();",
    "    }",
    "    return `${url.protocol}//${storageBucket()}.${url.host}/${key}`;",
    "  }",
    "",
    "  return `https://${storageBucket()}.s3.${storageRegion()}.amazonaws.com/${key}`;",
    "}",
    "",
  ].join("\n");
}
