import { action } from "@solidjs/router";
import { createProjectWorkspace, writeJson } from "@depths/stylyf-builder-core";
import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { createSupabaseServerClient } from "~/lib/supabase";
import { requireViewerIdentity } from "~/lib/server/resource-policy";

type StylyfSpec = Record<string, unknown>;

function splitList(input: string) {
  return input
    .split(",")
    .map(item => item.trim())
    .filter(Boolean);
}

function slug(input: string) {
  return input.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "item";
}

function title(input: string) {
  return input.replace(/[-_]+/g, " ").replace(/\b\w/g, char => char.toUpperCase());
}

function buildSpecFromPane(formData: FormData): StylyfSpec {
  const appName = String(formData.get("appName") ?? "Generated App").trim() || "Generated App";
  const appKind = String(formData.get("appKind") ?? "internal-tool").trim() || "internal-tool";
  const brief = String(formData.get("brief") ?? "").trim();
  const theme = String(formData.get("theme") ?? "opal").trim() || "opal";
  const objectName = slug(String(formData.get("objectName") ?? "records"));
  const fieldNames = splitList(String(formData.get("fields") ?? "title,status,summary"));
  const routeNames = splitList(String(formData.get("routes") ?? "Dashboard,Records,Settings"));

  const fields = fieldNames.map((name, index) => ({
    name: slug(name),
    type: index === 0 ? "short-text" : name.toLowerCase().includes("status") ? "status" : "long-text",
    required: index === 0,
    ...(name.toLowerCase().includes("status") ? { options: ["draft", "review", "approved"], default: "draft" } : {}),
  }));

  const objectTitle = title(objectName);
  const surfaces = routeNames.map((routeName, index) => {
    const routeSlug = slug(routeName);
    if (index === 0 && routeSlug === "dashboard") {
      return { name: title(routeName), kind: "dashboard", path: "/", audience: "user", title: title(routeName) };
    }
    if (routeSlug.includes("new") || routeSlug.includes("create")) {
      return { name: title(routeName), kind: "create", object: objectName, path: `/${objectName}/new`, audience: "user", title: title(routeName) };
    }
    if (routeSlug.includes("settings")) {
      return { name: title(routeName), kind: "settings", path: "/settings", audience: "user", title: "Settings" };
    }
    return { name: title(routeName), kind: "list", object: objectName, path: `/${objectName}`, audience: "user", title: title(routeName) || objectTitle };
  });

  return {
    version: "1.0",
    app: {
      name: appName,
      kind: appKind,
      description: brief || "Generated by Stylyf Builder.",
    },
    backend: { mode: "hosted" },
    media: { mode: "basic" },
    experience: {
      theme,
      mode: "light",
      radius: "trim",
      density: "comfortable",
      spacing: "tight",
    },
    objects: [
      {
        name: objectName,
        ownership: "user",
        visibility: "private",
        fields,
      },
    ],
    surfaces,
    navigation: {
      primary: surfaces.map(surface => ({
        label: String(surface.title ?? surface.name),
        href: String(surface.path),
        auth: "user",
      })),
    },
    deployment: { profile: "none" },
  };
}

function parseRawSpec(formData: FormData) {
  const raw = String(formData.get("rawSpec") ?? "").trim();
  if (!raw) return null;
  const parsed = JSON.parse(raw) as unknown;
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("Raw IR must be a JSON object.");
  }
  return parsed as StylyfSpec;
}

async function assertProject(projectId: string, userId: string) {
  const supabase = createSupabaseServerClient();
  const { data, error } = await supabase.from("projects").select("*").eq("id", projectId).eq("owner_id", userId).single();
  if (error) throw error;
  return data as Record<string, unknown>;
}

async function ensureWorkspace(project: Record<string, unknown>) {
  const existing = typeof project.workspacePath === "string" ? project.workspacePath : "";
  if (existing) {
    await mkdir(join(existing, "specs"), { recursive: true });
    return {
      root: existing,
      specs: join(existing, "specs"),
    };
  }

  const workspace = await createProjectWorkspace({
    projectId: String(project.id),
    name: String(project.name ?? "Untitled project"),
  });
  await createSupabaseServerClient().from("projects").update({ workspacePath: workspace.root }).eq("id", project.id);
  return workspace;
}

function buildChunkRecords(formData: FormData, spec: StylyfSpec) {
  const appName = String(formData.get("appName") ?? "Generated App").trim() || "Generated App";
  const appKind = String(formData.get("appKind") ?? "internal-tool").trim() || "internal-tool";
  const brief = String(formData.get("brief") ?? "").trim();
  const theme = String(formData.get("theme") ?? "opal").trim() || "opal";
  const objectName = slug(String(formData.get("objectName") ?? "records"));
  const fieldNames = splitList(String(formData.get("fields") ?? "title,status,summary"));
  const routeNames = splitList(String(formData.get("routes") ?? "Dashboard,Records,Settings"));

  return [
    {
      name: "brief",
      kind: "brief",
      fileName: "brief.chunk.json",
      content: {
        app: {
          name: appName,
          kind: appKind,
          description: brief || "Generated by Stylyf Builder.",
        },
      },
    },
    {
      name: "style",
      kind: "style",
      fileName: "style.chunk.json",
      content: {
        experience: {
          theme,
          mode: "light",
          radius: "trim",
          density: "comfortable",
          spacing: "tight",
        },
      },
    },
    {
      name: "data",
      kind: "data",
      fileName: "data.chunk.json",
      content: {
        objects: [
          {
            name: objectName,
            ownership: "user",
            visibility: "private",
            fields: fieldNames.map((name, index) => ({
              name: slug(name),
              type: index === 0 ? "short-text" : name.toLowerCase().includes("status") ? "status" : "long-text",
              required: index === 0,
              ...(name.toLowerCase().includes("status") ? { options: ["draft", "review", "approved"], default: "draft" } : {}),
            })),
          },
        ],
      },
    },
    {
      name: "routes",
      kind: "routes",
      fileName: "routes.chunk.json",
      content: {
        surfaces: Array.isArray(spec.surfaces) ? spec.surfaces : [],
        navigation: spec.navigation ?? {},
        meta: {
          requestedRoutes: routeNames,
        },
      },
    },
    {
      name: "full",
      kind: "raw",
      fileName: "full.chunk.json",
      content: spec,
    },
  ] as const;
}

export const saveIrDraft = action(async (projectId: string, formData: FormData) => {
  "use server";
  const { userId } = await requireViewerIdentity();
  const project = await assertProject(projectId, userId);
  const workspace = await ensureWorkspace(project);
  const spec = parseRawSpec(formData) ?? buildSpecFromPane(formData);
  const supabase = createSupabaseServerClient();
  await supabase.from("stylyf_specs").update({ is_active: false }).eq("project_id", projectId);
  const { data: latest } = await supabase
    .from("stylyf_specs")
    .select("version")
    .eq("project_id", projectId)
    .order("version", { ascending: false })
    .limit(1);
  const version = Number(latest?.[0]?.version ?? 0) + 1;
  const { error: specError } = await supabase.from("stylyf_specs").insert({
    project_id: projectId,
    kind: "full",
    spec,
    version,
    is_active: true,
    created_by: userId,
  });
  if (specError) throw specError;
  const chunks = buildChunkRecords(formData, spec);
  await supabase.from("stylyf_spec_chunks").update({ is_active: false }).eq("project_id", projectId);
  for (const chunk of chunks) {
    const specPath = join(workspace.specs, chunk.fileName);
    await writeJson(specPath, chunk.content);
    const { error: chunkError } = await supabase.from("stylyf_spec_chunks").insert({
      project_id: projectId,
      name: chunk.name,
      kind: chunk.kind,
      spec_text: JSON.stringify(chunk.content, null, 2),
      spec_path: specPath,
      version,
      is_active: true,
      created_by: userId,
    });
    if (chunkError) throw chunkError;
  }
  await writeJson(join(workspace.specs, "active.full.json"), spec);
  await writeJson(join(workspace.root, "stylyf.spec.json"), spec);
  await supabase.from("project_briefs").insert({
    project_id: projectId,
    brief_text: String(formData.get("brief") ?? ""),
    structured_summary: `App: ${String(formData.get("appName") ?? "")}; kind: ${String(formData.get("appKind") ?? "")}; theme: ${String(formData.get("theme") ?? "")}`,
    version,
    created_by: userId,
  });
  await supabase.from("briefs").insert({
    project_id: projectId,
    content: {
      appName: formData.get("appName"),
      appKind: formData.get("appKind"),
      brief: formData.get("brief"),
      theme: formData.get("theme"),
      objectName: formData.get("objectName"),
      fields: formData.get("fields"),
      routes: formData.get("routes"),
    },
    version,
    created_by: userId,
  });
  await supabase.from("agent_events").insert({
    project_id: projectId,
    owner_id: userId,
    type: "ir.saved",
    summary: `Saved active Stylyf IR draft v${version} and ${chunks.length} explicit spec chunks.`,
  });
  return { ok: true, version, spec: JSON.stringify(spec, null, 2) };
}, "ir.save-draft");
