import { action } from "@solidjs/router";
import { createProjectWorkspace, runCommand, writeJson } from "@depths/stylyf-builder-core";
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { createSupabaseServerClient } from "~/lib/supabase";
import { requireViewerIdentity } from "~/lib/server/resource-policy";

type StylyfStep = "validate" | "plan" | "generate";

function findRepoRoot(start = process.cwd()) {
  let current = resolve(start);
  for (let index = 0; index < 8; index += 1) {
    if (existsSync(join(current, "packages/stylyf-cli/dist/bin.js"))) return current;
    const next = dirname(current);
    if (next === current) break;
    current = next;
  }
  throw new Error("Unable to locate Stylyf CLI dist/bin.js from builder runtime.");
}

function createSpec(project: Record<string, unknown>) {
  const name = String(project.name ?? "Generated app");
  return {
    version: "1.0",
    app: {
      name,
      kind: "internal-tool",
      description: String(project.summary ?? "Generated by Stylyf Builder."),
    },
    backend: { mode: "hosted" },
    media: { mode: "basic" },
    experience: {
      theme: "opal",
      mode: "light",
      radius: "trim",
      density: "comfortable",
      spacing: "tight",
    },
    objects: [
      {
        name: "records",
        ownership: "user",
        visibility: "private",
        fields: [
          { name: "title", type: "short-text", required: true },
          { name: "status", type: "status", options: ["draft", "review", "approved"], default: "draft" },
          { name: "summary", type: "long-text" },
        ],
      },
    ],
    surfaces: [
      { name: "Dashboard", kind: "dashboard", path: "/", audience: "user", title: "Dashboard" },
      { name: "Records", kind: "list", object: "records", path: "/records", audience: "user", title: "Records" },
      { name: "New Record", kind: "create", object: "records", path: "/records/new", audience: "user", title: "New record" },
      { name: "Settings", kind: "settings", path: "/settings", audience: "user", title: "Settings" },
    ],
    navigation: {
      primary: [
        { label: "Dashboard", href: "/", auth: "user" },
        { label: "Records", href: "/records", auth: "user" },
        { label: "Settings", href: "/settings", auth: "user" },
      ],
    },
    deployment: { profile: "none" },
  };
}

async function getProject(projectId: string, userId: string) {
  const supabase = createSupabaseServerClient();
  const { data, error } = await supabase.from("projects").select("*").eq("id", projectId).eq("owner_id", userId).single();
  if (error) throw error;
  return data as Record<string, unknown>;
}

async function ensureWorkspace(project: Record<string, unknown>) {
  const supabase = createSupabaseServerClient();
  const existing = typeof project.workspacePath === "string" ? project.workspacePath : "";
  if (existing) {
    await mkdir(existing, { recursive: true });
    await mkdir(join(existing, "specs"), { recursive: true });
    await mkdir(join(existing, "logs"), { recursive: true });
    await mkdir(join(existing, "app"), { recursive: true });
    return {
      root: existing,
      specs: join(existing, "specs"),
      logs: join(existing, "logs"),
      app: join(existing, "app"),
    };
  }

  const workspace = await createProjectWorkspace({
    projectId: String(project.id),
    name: String(project.name ?? "Untitled project"),
  });
  await supabase.from("projects").update({ workspacePath: workspace.root }).eq("id", project.id);
  return workspace;
}

async function recordEvent(input: { projectId: string; userId: string; type: string; summary: string; artifactPath?: string }) {
  const supabase = createSupabaseServerClient();
  await supabase.from("agent_events").insert({
    project_id: input.projectId,
    owner_id: input.userId,
    type: input.type,
    summary: input.summary,
    artifact_path: input.artifactPath ?? null,
  });
}

async function recordCommand(input: {
  projectId: string;
  command: string;
  cwd: string;
  status: "completed" | "failed";
  exitCode: number | null;
  stdoutPath: string;
  stderrPath: string;
}) {
  const supabase = createSupabaseServerClient();
  await supabase.from("commands").insert({
    project_id: input.projectId,
    command: input.command,
    cwd: input.cwd,
    status: input.status,
    exit_code: input.exitCode,
    stdout_path: input.stdoutPath,
    stderr_path: input.stderrPath,
    completed_at: new Date().toISOString(),
  });
}

export const runStylyfProjectStep = action(async (projectId: string, step: StylyfStep) => {
  "use server";
  const { userId } = await requireViewerIdentity();
  const project = await getProject(projectId, userId);
  const workspace = await ensureWorkspace(project);
  const spec = createSpec(project);
  const specPath = join(workspace.specs, "stylyf.spec.json");
  await writeJson(specPath, spec);

  const repoRoot = findRepoRoot();
  const cliBin = join(repoRoot, "packages/stylyf-cli/dist/bin.js");
  const args =
    step === "validate"
      ? [cliBin, "validate", "--spec", specPath]
      : step === "plan"
        ? [cliBin, "plan", "--spec", specPath]
        : [cliBin, "generate", "--spec", specPath, "--target", workspace.app, "--no-install"];

  const command = await runCommand({
    command: "node",
    args,
    cwd: repoRoot,
    logsDir: workspace.logs,
  });

  await recordCommand({
    projectId,
    command: `node ${args.join(" ")}`,
    cwd: repoRoot,
    status: command.exitCode === 0 ? "completed" : "failed",
    exitCode: command.exitCode,
    stdoutPath: command.stdoutPath,
    stderrPath: command.stderrPath,
  });

  const eventSummary =
    command.exitCode === 0
      ? `Stylyf ${step} completed.`
      : `Stylyf ${step} failed with exit code ${command.exitCode ?? "unknown"}.`;
  await recordEvent({
    projectId,
    userId,
    type: `stylyf.${step}`,
    summary: eventSummary,
    artifactPath: command.stdoutPath,
  });

  if (step === "generate" && command.exitCode === 0) {
    await createSupabaseServerClient().from("projects").update({ status: "ready" }).eq("id", projectId);
    await writeFile(join(workspace.root, "handoff.md"), `# ${String(project.name ?? "Generated app")}\n\nGenerated by Stylyf Builder.\n\nWorkspace: ${workspace.app}\n`, "utf8");
  }

  return { ok: command.exitCode === 0, step, exitCode: command.exitCode };
}, "stylyf.run-project-step");
