// AUTO-GENERATED BY npm run generate:registry-shells
import { mergeProps, splitProps } from "solid-js";
import type { JSX } from "solid-js";
import { RegistryComponentShell } from "~/components/registry-component-shell";
import { registryItemBySlug } from "~/lib/registry";

export type ForgotPasswordProps = JSX.HTMLAttributes<HTMLElement> & {
  class?: string;
};

export function ForgotPassword(userProps: ForgotPasswordProps) {
  const props = mergeProps(userProps);
  const [local, others] = splitProps(props, ["class", "children"]);

  return (
    <RegistryComponentShell item={registryItemBySlug["forgot-password"]} class={local.class} {...others}>
      {local.children}
    </RegistryComponentShell>
  );
}
