export type BackendCatalogKind =
  | "capability"
  | "server-function"
  | "api-route"
  | "env-block"
  | "backend-snippet";

export type BackendCatalogEntry = {
  id: string;
  label: string;
  kind: BackendCatalogKind;
  area: string;
  description: string;
  summary: string;
  keywords: string[];
  snippet: string;
  props?: string[];
  sourcePath?: string;
};

export const backendCapabilityCatalog: Array<BackendCatalogEntry> = [
  {
    id: "database-postgres",
    label: "PostgreSQL Database Capability",
    kind: "capability",
    area: "Backend Capabilities",
    description: "Portable PostgreSQL capability using Drizzle ORM and the postgres driver.",
    summary: "Adds typed database wiring, Drizzle config, schema modules, and migration scripts for the portable Better Auth + Drizzle branch.",
    keywords: ["database", "postgres", "drizzle", "schema", "migration", "sql", "orm"],
    snippet:
      `"backend": {\n  "mode": "portable",\n  "portable": { "database": "postgres" }\n}`,
    props: ["backend.mode", "backend.portable.database"],
    sourcePath: "src/generators/backend/database.ts",
  },
  {
    id: "database-sqlite",
    label: "SQLite Database Capability",
    kind: "capability",
    area: "Backend Capabilities",
    description: "Portable SQLite capability using Drizzle ORM with the libsql driver for local files and later Turso-compatible upgrades.",
    summary: "Adds typed database wiring, Drizzle config, schema modules, and migration scripts for local Better Auth + Drizzle development.",
    keywords: ["database", "sqlite", "libsql", "drizzle", "local", "turso", "migration", "orm"],
    snippet:
      `"backend": {\n  "mode": "portable",\n  "portable": { "database": "sqlite" }\n}`,
    props: ["backend.mode", "backend.portable.database"],
    sourcePath: "src/generators/backend/database.ts",
  },
  {
    id: "database-supabase",
    label: "Supabase Data Capability",
    kind: "capability",
    area: "Backend Capabilities",
    description: "Hosted database capability using Supabase's SDK for data access instead of Drizzle.",
    summary: "Adds generated Supabase browser/server/admin clients and emits `supabase/schema.sql` for the fastest hosted path.",
    keywords: ["database", "supabase", "hosted", "sdk", "data api", "schema.sql", "postgres"],
    snippet: `"backend": {\n  "mode": "hosted"\n}`,
    props: ["backend.mode"],
    sourcePath: "src/generators/backend/supabase.ts",
  },
  {
    id: "auth-better-auth",
    label: "Better Auth Capability",
    kind: "capability",
    area: "Backend Capabilities",
    description: "Portable session-based Better Auth wiring integrated with SolidStart and Drizzle.",
    summary: "Generates auth server/client modules, Better Auth API route, and guard helpers for the portable branch.",
    keywords: ["auth", "better-auth", "session", "login", "signup", "protect", "session guard"],
    snippet:
      `"backend": {\n  "mode": "portable",\n  "portable": { "database": "sqlite" }\n}`,
    props: ["backend.mode", "backend.portable.database"],
    sourcePath: "src/generators/backend/auth.ts",
  },
  {
    id: "auth-supabase",
    label: "Supabase Auth Capability",
    kind: "capability",
    area: "Backend Capabilities",
    description: "Hosted session-based auth wiring using `@supabase/ssr` and `@supabase/supabase-js`.",
    summary: "Generates Supabase browser/server/auth modules, auth API routes, callback handling, middleware, and guard helpers.",
    keywords: ["auth", "supabase", "ssr", "session", "email password", "email otp", "signup", "signin"],
    snippet: `"backend": {\n  "mode": "hosted"\n}`,
    props: ["backend.mode"],
    sourcePath: "src/generators/backend/supabase.ts",
  },
  {
    id: "storage-s3",
    label: "S3 Storage Capability",
    kind: "capability",
    area: "Backend Capabilities",
    description: "S3-compatible object storage capability using AWS SDK v3 and presigned upload helpers.",
    summary: "Generates a server-owned storage client and browser upload handshake primitives, with Tigris-friendly AWS-compatible env aliases.",
    keywords: ["storage", "s3", "upload", "presign", "bucket", "object storage", "aws sdk", "tigris"],
    snippet:
      `"media": {\n  "mode": "rich"\n}`,
    props: ["media.mode"],
    sourcePath: "src/generators/backend/storage.ts",
  },
  {
    id: "env-contract",
    label: "Typed Env Contract Capability",
    kind: "capability",
    area: "Backend Capabilities",
    description: "Generated typed environment contract for app, database, auth, and storage configuration.",
    summary: "Emits `.env.example` and server-safe env helpers with fail-fast accessors.",
    keywords: ["env", "environment", "config", "typed", "server env", "dotenv"],
    snippet: `stylyf generate --spec stylyf.spec.json --target ./my-app`,
    props: [".env.example", "src/lib/env.ts"],
    sourcePath: "src/generators/backend/env.ts",
  },
  {
    id: "resource-recipes",
    label: "Resource Recipe Foundations",
    kind: "capability",
    area: "SpecV04 Effects",
    description: "Generalized resource grammar for repeatable app entities, relations, and baseline CRUD surfaces.",
    summary: "Drives schema output, generated CRUD server modules, and resource-aware route/page scaffolds from one generalized source of truth.",
    keywords: ["resource", "relation", "crud", "entity", "table", "recipe", "v0.4"],
    snippet:
      `"objects": [\n  {\n    "name": "records",\n    "ownership": "user",\n    "fields": [{ "name": "title", "type": "short-text", "required": true }]\n  }\n]`,
    props: ["objects", "fields", "ownership", "visibility", "media"],
    sourcePath: "src/spec/types.ts",
  },
  {
    id: "ownership-policy-foundations",
    label: "Ownership And Policy Foundations",
    kind: "capability",
    area: "SpecV04 Effects",
    description: "Generalized ownership and access presets for resource-oriented apps.",
    summary: "Provides a broad policy grammar that now emits portable ownership guards and hosted Supabase RLS policy SQL without baking in product-specific semantics.",
    keywords: ["ownership", "policy", "access", "owner", "workspace", "public", "rls", "v0.4"],
    snippet:
      `"objects": [\n  { "name": "records", "ownership": "user", "visibility": "mixed" }\n]`,
    props: ["objects.ownership", "objects.visibility"],
    sourcePath: "src/spec/types.ts",
  },
  {
    id: "attachment-lifecycle-foundations",
    label: "Attachment Lifecycle Foundations",
    kind: "capability",
    area: "SpecV04 Effects",
    description: "Generalized attachment grammar for file and media lifecycles on top of the shared S3/Tigris substrate.",
    summary: "Declares attachments as resource mechanics rather than niche media-product features and emits metadata tables plus presign, confirm, replace, and delete flows.",
    keywords: ["attachment", "asset", "upload", "metadata", "storage", "s3", "tigris", "v0.4"],
    snippet:
      `"media": { "mode": "rich" },\n"objects": [\n  {\n    "name": "records",\n    "media": [\n      { "name": "heroImage", "kind": "image" },\n      { "name": "sourceFiles", "kind": "document", "multiple": true }\n    ]\n  }\n]`,
    props: ["media.mode", "objects.media"],
    sourcePath: "src/spec/types.ts",
  },
  {
    id: "form-mutation-foundations",
    label: "Form And Mutation Foundations",
    kind: "capability",
    area: "SpecV04 Effects",
    description: "Resource-first mutation surface for create/edit/delete flows and future generated forms.",
    summary: "Keeps Stylyf aligned with Solid Router action semantics while generating repeatable create/edit page shells, form components, and server-side form handlers.",
    keywords: ["form", "mutation", "action", "validation", "resource", "solidstart", "v0.4"],
    snippet:
      `"surfaces": [\n  { "name": "New Record", "kind": "create", "object": "records", "path": "/records/new" },\n  { "name": "Edit Record", "kind": "edit", "object": "records", "path": "/records/:id/edit" }\n]`,
    props: ["surfaces.kind", "surfaces.object", "surfaces.path"],
    sourcePath: "src/spec/types.ts",
  },
  {
    id: "workflow-foundations",
    label: "Workflow And Event Foundations",
    kind: "capability",
    area: "SpecV04 Effects",
    description: "Generalized state transition grammar for approvals, publishing, onboarding, and other repeatable app workflows.",
    summary: "Declares workflows, transitions, emitted events, and notification audiences in a broad way and emits transition actions plus shared event-log and notification surfaces.",
    keywords: ["workflow", "state", "transition", "event", "notification", "approval", "publish", "v0.4"],
    snippet:
      `"flows": [\n  {\n    "name": "recordLifecycle",\n    "object": "records",\n    "kind": "approval",\n    "states": ["draft", "review", "approved"]\n  }\n]`,
    props: ["flows.name", "flows.object", "flows.kind", "flows.states"],
    sourcePath: "src/spec/types.ts",
  },
];

export const backendServerTemplateCatalog: Array<BackendCatalogEntry> = [
  {
    id: "server-list-query",
    label: "List Query Server Module",
    kind: "server-function",
    area: "Server Functions",
    description: "Server-side list query using Solid Router query semantics and optional auth guards.",
    summary: "Best default for resource indexes, inboxes, audit logs, and filtered lists.",
    keywords: ["query", "list", "server", "solidstart", "createAsync", "resource index"],
    snippet:
      `export const listRecords = query(async () => {\n  "use server";\n  return db.select().from(records);\n}, "records.list");`,
    props: ["name", "resource", "auth", "filters"],
    sourcePath: "src/templates/server-functions/list-query.ts.tpl",
  },
  {
    id: "server-detail-query",
    label: "Detail Query Server Module",
    kind: "server-function",
    area: "Server Functions",
    description: "Server-side detail query for fetching a single record by id or slug.",
    summary: "Use for resource detail pages and master-detail side panels.",
    keywords: ["query", "detail", "record", "server", "resource detail"],
    snippet:
      `export const getRecord = query(async (id: string) => {\n  "use server";\n  return db.query.records.findFirst({ where: eq(records.id, id) });\n}, "records.detail");`,
    props: ["name", "resource", "auth", "key"],
    sourcePath: "src/templates/server-functions/detail-query.ts.tpl",
  },
  {
    id: "server-create-action",
    label: "Create Action Server Module",
    kind: "server-function",
    area: "Server Functions",
    description: "Mutation action for creating a record, optionally guarded by session requirements.",
    summary: "Use for forms, modal creates, and onboarding flows.",
    keywords: ["action", "create", "mutation", "server", "form submit"],
    snippet:
      `export const createRecord = action(async (input: CreateRecordInput) => {\n  "use server";\n  return db.insert(records).values(input).returning();\n});`,
    props: ["name", "resource", "auth", "validation"],
    sourcePath: "src/templates/server-functions/create-action.ts.tpl",
  },
  {
    id: "server-update-action",
    label: "Update Action Server Module",
    kind: "server-function",
    area: "Server Functions",
    description: "Mutation action for updating a record using Drizzle and SolidStart server actions.",
    summary: "Use for settings forms, inline editing, and resource detail edits.",
    keywords: ["action", "update", "mutation", "server", "edit"],
    snippet:
      `export const updateRecord = action(async (input: UpdateRecordInput) => {\n  "use server";\n  return db.update(records).set(input).where(eq(records.id, input.id)).returning();\n});`,
    props: ["name", "resource", "auth", "validation"],
    sourcePath: "src/templates/server-functions/update-action.ts.tpl",
  },
  {
    id: "server-delete-action",
    label: "Delete Action Server Module",
    kind: "server-function",
    area: "Server Functions",
    description: "Mutation action for deleting a record, optionally paired with audit or ownership checks.",
    summary: "Use for destructive actions, archive flows, and bulk removal baselines.",
    keywords: ["action", "delete", "remove", "mutation", "server", "destructive"],
    snippet:
      `export const deleteRecord = action(async (id: string) => {\n  "use server";\n  return db.delete(records).where(eq(records.id, id)).returning();\n});`,
    props: ["name", "resource", "auth"],
    sourcePath: "src/templates/server-functions/delete-action.ts.tpl",
  },
  {
    id: "server-upload-handshake-action",
    label: "Upload Handshake Action",
    kind: "server-function",
    area: "Server Functions",
    description: "Server-side action for issuing presigned upload information to the browser.",
    summary: "Use as the baseline bridge between browser uploads and S3-compatible storage.",
    keywords: ["upload", "presign", "action", "storage", "s3", "server"],
    snippet:
      `export const createUpload = action(async (input: UploadIntent) => {\n  "use server";\n  return createPresignedUpload(input);\n});`,
    props: ["name", "auth", "contentTypes"],
    sourcePath: "src/templates/server-functions/upload-handshake-action.ts.tpl",
  },
  {
    id: "server-session-guard",
    label: "Require Session Guard",
    kind: "server-function",
    area: "Server Functions",
    description: "Server guard helper that enforces an authenticated session in either backend mode.",
    summary: "Use to protect queries, actions, and route-side server logic whether the app uses Better Auth or Supabase.",
    keywords: ["auth", "session", "guard", "server", "better-auth", "supabase", "protected"],
    snippet:
      `const session = await requireSession();\nif (!session) throw redirect("/login");`,
    props: ["redirectTo", "role"],
    sourcePath: "src/generators/backend/supabase.ts",
  },
];

export const backendApiRouteCatalog: Array<BackendCatalogEntry> = [
  {
    id: "api-auth-handler",
    label: "Better Auth Handler Route",
    kind: "api-route",
    area: "API Routes",
    description: "Catch-all auth API route used by Better Auth in SolidStart.",
    summary: "Mounts the generated auth instance at `/api/auth/[...auth]`.",
    keywords: ["api", "auth", "better-auth", "handler", "solidstart"],
    snippet:
      `import { toSolidStartHandler } from "better-auth/solid-start";\nimport { auth } from "~/lib/auth";\n\nexport const { GET, POST } = toSolidStartHandler(auth);`,
    props: ["path", "method"],
    sourcePath: "src/templates/api-routes/auth-mount.ts.tpl",
  },
  {
    id: "api-supabase-auth-routes",
    label: "Supabase Auth Route Set",
    kind: "api-route",
    area: "API Routes",
    description: "Generated auth API routes for Supabase password and email OTP flows.",
    summary: "Mounts explicit JSON routes for session lookup, sign-up, sign-in, OTP request, OTP verify, and sign-out.",
    keywords: ["api", "auth", "supabase", "signup", "signin", "otp", "session", "signout"],
    snippet:
      `POST /api/auth/sign-up/password\nPOST /api/auth/sign-in/password\nPOST /api/auth/sign-in/otp\nPOST /api/auth/verify-otp\nPOST /api/auth/sign-out\nGET /api/auth/session`,
    props: ["path", "method", "name", "auth"],
    sourcePath: "src/generators/backend/supabase.ts",
  },
  {
    id: "api-json-route",
    label: "JSON API Route",
    kind: "api-route",
    area: "API Routes",
    description: "Simple JSON route template for app-owned endpoints and external clients.",
    summary: "Use for explicit machine-facing endpoints that should not be server actions.",
    keywords: ["api", "json", "route", "endpoint", "http"],
    snippet:
      `export async function GET() {\n  return new Response(JSON.stringify({ ok: true }), {\n    headers: { "content-type": "application/json" },\n  });\n}`,
    props: ["path", "method", "name"],
    sourcePath: "src/templates/api-routes/json.ts.tpl",
  },
  {
    id: "api-webhook-route",
    label: "Webhook Route",
    kind: "api-route",
    area: "API Routes",
    description: "POST route template for external webhook receivers with signature validation hooks.",
    summary: "Use for webhook-style integrations and callback receivers.",
    keywords: ["api", "webhook", "callback", "route", "post"],
    snippet:
      `export async function POST(event: APIEvent) {\n  const payload = await event.request.text();\n  return new Response(null, { status: 204 });\n}`,
    props: ["path", "name", "signature"],
    sourcePath: "src/templates/api-routes/webhook.ts.tpl",
  },
  {
    id: "api-presign-upload-route",
    label: "Presigned Upload Route",
    kind: "api-route",
    area: "API Routes",
    description: "JSON POST route that returns a presigned S3 upload payload.",
    summary: "Use when the app wants an explicit upload signing endpoint instead of a server action only.",
    keywords: ["api", "upload", "presign", "s3", "route"],
    snippet:
      `export async function POST(event: APIEvent) {\n  const input = await event.request.json();\n  const signed = await createPresignedUpload(input);\n  return Response.json(signed);\n}`,
    props: ["path", "name", "auth"],
    sourcePath: "src/templates/api-routes/presign-upload.ts.tpl",
  },
];

export const backendEnvCatalog: Array<BackendCatalogEntry> = [
  {
    id: "env-app-core",
    label: "App Core Env Block",
    kind: "env-block",
    area: "Environment",
    description: "Core app-level variables shared across generated full-stack apps.",
    summary: "Provides base URL and runtime environment variables used by auth and other capabilities.",
    keywords: ["env", "app", "base url", "node env", "config"],
    snippet: `APP_BASE_URL=\nNODE_ENV=development`,
    props: ["APP_BASE_URL", "NODE_ENV"],
    sourcePath: "src/generators/backend/env.ts",
  },
  {
    id: "env-postgres",
    label: "PostgreSQL Env Block",
    kind: "env-block",
    area: "Environment",
    description: "Database connection variables for the generated Postgres + Drizzle stack.",
    summary: "Provides the connection URL required by Drizzle and the postgres driver.",
    keywords: ["env", "database", "postgres", "drizzle", "database_url"],
    snippet: `DATABASE_URL=postgres://postgres:postgres@localhost:5432/app`,
    props: ["DATABASE_URL"],
    sourcePath: "src/generators/backend/env.ts",
  },
  {
    id: "env-sqlite",
    label: "SQLite Env Block",
    kind: "env-block",
    area: "Environment",
    description: "Database connection variables for the generated SQLite + libsql stack.",
    summary: "Uses a file-backed `DATABASE_URL` locally and an optional auth token for later remote libsql providers such as Turso.",
    keywords: ["env", "database", "sqlite", "libsql", "turso", "database_url", "database_auth_token"],
    snippet: `DATABASE_URL=file:./local.db\nDATABASE_AUTH_TOKEN=`,
    props: ["DATABASE_URL", "DATABASE_AUTH_TOKEN"],
    sourcePath: "src/generators/backend/env.ts",
  },
  {
    id: "env-supabase",
    label: "Supabase Env Block",
    kind: "env-block",
    area: "Environment",
    description: "Hosted auth and data configuration for the generated Supabase branch.",
    summary: "Provides the project URL, publishable key, secret key, and client-exposed aliases used by the generated Supabase modules.",
    keywords: ["env", "supabase", "publishable", "secret", "url", "ssr", "auth", "data"],
    snippet:
      `SUPABASE_URL=https://your-project-ref.supabase.co\nSUPABASE_PUBLISHABLE_KEY=sb_publishable_xxx\nSUPABASE_SECRET_KEY=sb_secret_xxx\nVITE_SUPABASE_URL=https://your-project-ref.supabase.co\nVITE_SUPABASE_PUBLISHABLE_KEY=sb_publishable_xxx`,
    props: [
      "SUPABASE_URL",
      "SUPABASE_PUBLISHABLE_KEY",
      "SUPABASE_SECRET_KEY",
      "VITE_SUPABASE_URL",
      "VITE_SUPABASE_PUBLISHABLE_KEY",
    ],
    sourcePath: "src/generators/backend/env.ts",
  },
  {
    id: "env-better-auth",
    label: "Better Auth Env Block",
    kind: "env-block",
    area: "Environment",
    description: "Auth secret and public URL variables required by Better Auth.",
    summary: "Provides the secret and canonical auth URL for generated auth wiring.",
    keywords: ["env", "auth", "better-auth", "secret", "url"],
    snippet: `BETTER_AUTH_SECRET=\nBETTER_AUTH_URL=http://localhost:3000`,
    props: ["BETTER_AUTH_SECRET", "BETTER_AUTH_URL"],
    sourcePath: "src/generators/backend/env.ts",
  },
  {
    id: "env-s3",
    label: "S3 / Tigris Storage Env Block",
    kind: "env-block",
    area: "Environment",
    description: "S3-compatible configuration block used by the generated storage capability.",
    summary: "Supports AWS S3 and endpoint-based compatible providers like Tigris, including AWS-style env aliases.",
    keywords: ["env", "storage", "s3", "bucket", "region", "endpoint", "spaces", "tigris"],
    snippet:
      `S3_BUCKET=\nAWS_REGION=auto\nAWS_ACCESS_KEY_ID=\nAWS_SECRET_ACCESS_KEY=\nAWS_ENDPOINT_URL_S3=https://t3.storage.dev\nS3_FORCE_PATH_STYLE=false\nS3_PUBLIC_BASE_URL=`,
    props: [
      "S3_BUCKET",
      "AWS_REGION",
      "AWS_ACCESS_KEY_ID",
      "AWS_SECRET_ACCESS_KEY",
      "AWS_ENDPOINT_URL_S3",
      "S3_FORCE_PATH_STYLE",
      "S3_PUBLIC_BASE_URL",
    ],
    sourcePath: "src/generators/backend/env.ts",
  },
];

export const backendSnippetCatalog: Array<BackendCatalogEntry> = [
  {
    id: "snippet-v04-spec-workflow",
    label: "v0.4 Spec Workflow",
    kind: "backend-snippet",
    area: "Operator Workflow",
    description: "Create, validate, inspect, and generate from a small v0.4 spec.",
    summary: "The preferred v0.4 operator loop: author the intent-level spec, inspect the plan, then generate ordinary SolidStart source.",
    keywords: ["v0.4", "spec", "workflow", "new", "validate", "plan", "generate", "compiler"],
    snippet:
      `stylyf new internal-tool --name "Acme Ops" --backend portable --media rich --output stylyf.spec.json\nstylyf validate --spec stylyf.spec.json\nstylyf plan --spec stylyf.spec.json\nstylyf generate --spec stylyf.spec.json --target ./my-app`,
    props: ["--spec", "--target", "--backend", "--media"],
    sourcePath: "src/spec/types.ts",
  },
  {
    id: "snippet-canonical-portable-example",
    label: "Canonical Portable v0.4 Example",
    kind: "backend-snippet",
    area: "Operator Workflow",
    description: "The clearest example set for the Better Auth + Drizzle + Tigris path.",
    summary: "Points operators toward the v0.4 portable examples and SQLite smoke path.",
    keywords: ["portable", "example", "canonical", "better-auth", "drizzle", "sqlite", "tigris"],
    snippet:
      `packages/stylyf-cli/examples/v0.4/internal-tool.basic.json\npackages/stylyf-cli/examples/v0.4/cms-site.basic.json\npackages/stylyf-cli/examples/v0.4/free-saas-tool.basic.json`,
    props: ["portable", "local", "sqlite"],
    sourcePath: "examples/README.md",
  },
  {
    id: "snippet-canonical-hosted-example",
    label: "Canonical Hosted v0.4 Example",
    kind: "backend-snippet",
    area: "Operator Workflow",
    description: "The clearest example set for the Supabase + Tigris hosted path.",
    summary: "Points operators toward hosted specs that compile to Supabase Auth, Supabase data SDK, and Tigris/S3-compatible storage.",
    keywords: ["hosted", "example", "canonical", "supabase", "tigris", "managed", "spec"],
    snippet:
      `stylyf new internal-tool --name "Hosted Ops" --backend hosted --media rich --output hosted.spec.json`,
    props: ["hosted", "supabase", "spec"],
    sourcePath: "examples/README.md",
  },
  {
    id: "snippet-v0-resource-grammar",
    label: "v0.4 Resource Grammar",
    kind: "backend-snippet",
    area: "SpecV04 DSL",
    description: "Example public spec block showing objects, ownership, fields, media, and workflow intent together.",
    summary: "Useful as the starting point for resource-centric apps when you want Stylyf to derive schema, CRUD, policy, attachment, and workflow surfaces from one block.",
    keywords: ["resource", "ownership", "attachment", "relation", "workflow", "v0.4"],
    snippet:
      `"objects": [\n  {\n    "name": "records",\n    "visibility": "mixed",\n    "ownership": "user",\n    "fields": [\n      { "name": "title", "type": "short-text", "required": true },\n      { "name": "status", "type": "status", "options": ["draft", "review", "published"] }\n    ],\n    "media": [{ "name": "coverImage", "kind": "image" }]\n  }\n],\n"flows": [{ "name": "recordLifecycle", "object": "records", "kind": "approval" }]`,
    props: ["objects", "fields", "ownership", "media", "flows"],
    sourcePath: "src/spec/types.ts",
  },
  {
    id: "snippet-v0-resource-form-routes",
    label: "v0.4 Resource Create And Edit Routes",
    kind: "backend-snippet",
    area: "SpecV04 DSL",
    description: "Example public surfaces block for generated create and edit routes driven by one object definition.",
    summary: "Useful when you want Stylyf to emit page shells plus generated form components for ordinary resource mutations.",
    keywords: ["resource", "create", "edit", "form", "route", "page shell", "v0.4"],
    snippet:
      `"surfaces": [\n  { "name": "New Record", "kind": "create", "object": "records", "path": "/records/new" },\n  { "name": "Edit Record", "kind": "edit", "object": "records", "path": "/records/:id/edit" }\n]`,
    props: ["surfaces.name", "surfaces.kind", "surfaces.object", "surfaces.path"],
    sourcePath: "src/spec/types.ts",
  },
  {
    id: "snippet-v0-attachment-lifecycle",
    label: "v0.4 Attachment Lifecycle",
    kind: "backend-snippet",
    area: "SpecV04 DSL",
    description: "Example public object media block showing the generalized asset lifecycle surface.",
    summary: "Maps to generated metadata tables plus presign, confirm, replace, and delete helpers while keeping storage server-owned.",
    keywords: ["attachment", "asset", "upload", "presign", "confirm", "replace", "delete", "v0.4"],
    snippet:
      `"media": { "mode": "rich" },\n"objects": [\n  {\n    "name": "records",\n    "media": [{ "name": "coverImage", "kind": "image", "required": false }]\n  }\n]`,
    props: ["media.mode", "objects.media.name", "objects.media.kind", "objects.media.required"],
    sourcePath: "src/spec/types.ts",
  },
  {
    id: "snippet-v0-workflow-events-notifications",
    label: "v0.4 Workflow Events And Notifications",
    kind: "backend-snippet",
    area: "SpecV04 DSL",
    description: "Example public flow block for generated workflow transitions.",
    summary: "Useful when you want generated transition actions plus shared event-log and notification queries/actions in either backend branch.",
    keywords: ["workflow", "event", "notification", "transition", "status", "audit", "v0.4"],
    snippet:
      `"flows": [\n  {\n    "name": "recordLifecycle",\n    "object": "records",\n    "kind": "approval",\n    "states": ["draft", "review", "approved"],\n    "transitions": [\n      { "name": "submitForReview", "from": "draft", "to": "review", "actor": "owner" }\n    ]\n  }\n]`,
    props: ["flows.name", "flows.object", "flows.kind", "flows.states", "flows.transitions"],
    sourcePath: "src/spec/types.ts",
  },
  {
    id: "snippet-drizzle-db-module",
    label: "Drizzle DB Module",
    kind: "backend-snippet",
    area: "Backend Snippets",
    description: "Typed Drizzle database module using the postgres driver and generated env contract.",
    summary: "Provides the shared DB client and schema wiring for the rest of the generated app.",
    keywords: ["snippet", "db", "drizzle", "postgres", "module"],
    snippet:
      `import postgres from "postgres";\nimport { drizzle } from "drizzle-orm/postgres-js";\nimport { env } from "~/lib/env";\n\nconst client = postgres(env.DATABASE_URL);\nexport const db = drizzle(client);`,
    props: ["DATABASE_URL"],
    sourcePath: "src/generators/backend/database.ts",
  },
  {
    id: "snippet-libsql-db-module",
    label: "libSQL DB Module",
    kind: "backend-snippet",
    area: "Backend Snippets",
    description: "Typed Drizzle database module using libsql for local SQLite files and remote Turso-compatible connections.",
    summary: "Provides the shared DB client and schema wiring for the generated local auth+DB path.",
    keywords: ["snippet", "db", "drizzle", "sqlite", "libsql", "module", "turso"],
    snippet:
      `import { createClient } from "@libsql/client";\nimport { drizzle } from "drizzle-orm/libsql";\nimport { env } from "~/lib/env";\n\nconst client = createClient({ url: env.DATABASE_URL, authToken: env.DATABASE_AUTH_TOKEN });\nexport const db = drizzle(client);`,
    props: ["DATABASE_URL", "DATABASE_AUTH_TOKEN"],
    sourcePath: "src/generators/backend/database.ts",
  },
  {
    id: "snippet-better-auth-module",
    label: "Better Auth Module",
    kind: "backend-snippet",
    area: "Backend Snippets",
    description: "Auth module wiring Better Auth to Drizzle and the generated env helpers.",
    summary: "Provides a readable baseline auth setup instead of hiding auth behind a Stylyf wrapper.",
    keywords: ["snippet", "auth", "better-auth", "drizzle", "module", "sqlite", "pg"],
    snippet:
      `import { betterAuth } from "better-auth";\nimport { drizzleAdapter } from "better-auth/adapters/drizzle";\nimport { db, schema } from "~/lib/db";\n\nexport const auth = betterAuth({ database: drizzleAdapter(db, { provider: "sqlite", schema }) });`,
    props: ["BETTER_AUTH_SECRET", "BETTER_AUTH_URL"],
    sourcePath: "src/generators/backend/auth.ts",
  },
  {
    id: "snippet-supabase-browser-client",
    label: "Supabase Browser Client",
    kind: "backend-snippet",
    area: "Backend Snippets",
    description: "Browser-side Supabase client created with `@supabase/ssr` and the generated public env contract.",
    summary: "Provides the browser auth/data client for the fast hosted path.",
    keywords: ["snippet", "supabase", "browser", "client", "ssr", "publishable"],
    snippet:
      `import { createBrowserClient } from "@supabase/ssr";\nimport { publicEnv } from "~/lib/env";\n\nexport const supabase = createBrowserClient(publicEnv.VITE_SUPABASE_URL, publicEnv.VITE_SUPABASE_PUBLISHABLE_KEY);`,
    props: ["VITE_SUPABASE_URL", "VITE_SUPABASE_PUBLISHABLE_KEY"],
    sourcePath: "src/generators/backend/supabase.ts",
  },
  {
    id: "snippet-supabase-server-client",
    label: "Supabase Server And Admin Clients",
    kind: "backend-snippet",
    area: "Backend Snippets",
    description: "Request-scoped SSR client plus separate secret-key admin client for Supabase.",
    summary: "Keeps session cookies on the SSR path and privileged operations on a server-only client.",
    keywords: ["snippet", "supabase", "server", "admin", "secret", "ssr", "cookies"],
    snippet:
      `const supabase = createServerClient(env.SUPABASE_URL, env.SUPABASE_PUBLISHABLE_KEY, { cookies: { getAll, setAll } });\nconst admin = createClient(env.SUPABASE_URL, env.SUPABASE_SECRET_KEY, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } });`,
    props: ["SUPABASE_URL", "SUPABASE_PUBLISHABLE_KEY", "SUPABASE_SECRET_KEY"],
    sourcePath: "src/generators/backend/supabase.ts",
  },
  {
    id: "snippet-supabase-auth-module",
    label: "Supabase Auth Module",
    kind: "backend-snippet",
    area: "Backend Snippets",
    description: "Auth helpers for the generated Supabase branch, including password and email OTP flows.",
    summary: "Provides sign-up, sign-in, email OTP request/verify, session helpers, sign-out, and route guards.",
    keywords: ["snippet", "auth", "supabase", "password", "otp", "signup", "signin", "guard"],
    snippet:
      `export async function signInWithPassword(input: { email: string; password: string }) {\n  return createSupabaseServerClient().auth.signInWithPassword(input);\n}\n\nexport async function requestEmailOtp(input: { email: string }) {\n  return createSupabaseServerClient().auth.signInWithOtp({ email: input.email, options: { shouldCreateUser: true } });\n}`,
    props: ["emailPassword", "emailOtp", "protect"],
    sourcePath: "src/generators/backend/supabase.ts",
  },
  {
    id: "snippet-s3-storage-module",
    label: "S3 Storage Module",
    kind: "backend-snippet",
    area: "Backend Snippets",
    description: "Storage capability module using S3Client and presigned upload helpers.",
    summary: "Provides the baseline bridge to S3-compatible object stores without exposing credentials to the browser.",
    keywords: ["snippet", "storage", "s3", "presign", "aws sdk", "module", "tigris"],
    snippet:
      `const client = new S3Client({ region: env.AWS_REGION ?? env.S3_REGION, endpoint: env.AWS_ENDPOINT_URL_S3 || env.S3_ENDPOINT || undefined });\nexport async function createPresignedUpload(input: UploadIntent) {\n  return getSignedUrl(client, new PutObjectCommand({ Bucket: env.S3_BUCKET, Key: input.key }));\n}`,
    props: ["S3_BUCKET", "AWS_REGION", "AWS_ENDPOINT_URL_S3"],
    sourcePath: "src/generators/backend/storage.ts",
  },
  {
    id: "snippet-typed-env-module",
    label: "Typed Env Module",
    kind: "backend-snippet",
    area: "Backend Snippets",
    description: "Server-side env helper that fails fast on missing required variables.",
    summary: "Provides a light, explicit env contract without bringing in a heavy runtime framework first.",
    keywords: ["snippet", "env", "typed", "module", "config"],
    snippet:
      `function required(name: string) {\n  const value = process.env[name];\n  if (!value) throw new Error(\`Missing env: \${name}\`);\n  return value;\n}\n\nexport const env = { DATABASE_URL: required("DATABASE_URL") };`,
    props: ["required", "optional"],
    sourcePath: "src/generators/backend/env.ts",
  },
];
