import type { SearchableEntry } from "../search/index.js";

export const patternCatalog: SearchableEntry[] = [
  {
    id: "pattern-portable-sqlite-smoke",
    label: "Portable SQLite Smoke Path",
    kind: "pattern",
    area: "v1.0 Patterns",
    description: "Default local backend dogfood path using Better Auth, Drizzle, SQLite/libsql, and optional S3-compatible storage.",
    summary: "Use this when you want the fastest local full-stack smoke test before moving to hosted services.",
    keywords: ["portable", "sqlite", "better-auth", "drizzle", "local", "smoke", "database", "auth"],
    sourcePath: "src/compiler/expand.ts",
    snippet: "\"backend\": { \"mode\": \"portable\", \"portable\": { \"database\": \"sqlite\" } }",
    searchText: "portable sqlite better-auth drizzle local smoke database auth",
  },
  {
    id: "pattern-hosted-supabase-tigris",
    label: "Hosted Supabase + Tigris Path",
    kind: "pattern",
    area: "v1.0 Patterns",
    description: "Managed backend path using Supabase Auth, Supabase SDK data access, and Tigris/S3-compatible object storage.",
    summary: "Use this when you want the fastest deployment path with managed auth/data and presigned object storage.",
    keywords: ["hosted", "supabase", "tigris", "s3", "managed", "auth", "data", "storage"],
    sourcePath: "src/compiler/expand.ts",
    snippet: "\"backend\": { \"mode\": \"hosted\" }, \"media\": { \"mode\": \"rich\" }",
    searchText: "hosted supabase tigris s3 managed auth data storage",
  },
  {
    id: "pattern-rich-media-attachments",
    label: "Rich Media Attachments",
    kind: "pattern",
    area: "v1.0 Patterns",
    description: "Object-level media attachments compiled into metadata tables, presign routes, confirm, replace, and delete flows.",
    summary: "Use this for apps that need images, documents, or file lifecycle handling without exposing raw bucket credentials.",
    keywords: ["media", "attachments", "upload", "presign", "metadata", "replace", "delete", "tigris", "s3"],
    sourcePath: "src/generators/backend/attachments.ts",
    snippet: "\"media\": { \"mode\": \"rich\" }",
    searchText: "media attachments upload presign metadata replace delete tigris s3",
  },
  {
    id: "pattern-internal-ops-dashboard",
    label: "Internal Ops Dashboard",
    kind: "pattern",
    area: "v1.1 Builder Patterns",
    description: "Authenticated dashboard plus queue/create/settings surfaces for operational ownership and triage.",
    summary: "Use this when the prompt asks for admin consoles, review queues, CRM-like workflows, or internal operations.",
    keywords: ["internal", "ops", "dashboard", "queue", "approval", "triage", "admin"],
    sourcePath: "examples/v1.0/pattern-internal-ops-dashboard.json",
    snippet: "stylyf validate --spec examples/v1.0/pattern-internal-ops-dashboard.json",
    searchText: "internal ops dashboard queue approval triage admin console operations",
  },
  {
    id: "pattern-rating-review-app",
    label: "Rating and Review App",
    kind: "pattern",
    area: "v1.1 Builder Patterns",
    description: "Public discovery, authenticated submission, rich media attachments, ratings, and moderation.",
    summary: "Use this for broad user-generated-content apps, not only media rating niches.",
    keywords: ["rating", "review", "ugc", "moderation", "submission", "public", "media"],
    sourcePath: "examples/v1.0/pattern-rating-review-app.json",
    snippet: "stylyf validate --spec examples/v1.0/pattern-rating-review-app.json",
    searchText: "rating review ugc moderation submission public media community",
  },
  {
    id: "pattern-media-submission-queue",
    label: "Media Submission Queue",
    kind: "pattern",
    area: "v1.1 Builder Patterns",
    description: "Generalized rich-file intake with presigned upload storage, review queue, and detail surfaces.",
    summary: "Use this for any app where users or operators upload files that need review before downstream use.",
    keywords: ["media", "submission", "queue", "upload", "review", "presigned", "asset"],
    sourcePath: "examples/v1.0/pattern-media-submission-queue.json",
    snippet: "stylyf validate --spec examples/v1.0/pattern-media-submission-queue.json",
    searchText: "media submission queue upload review presigned asset files intake",
  },
  {
    id: "pattern-lightweight-cms",
    label: "Lightweight CMS",
    kind: "pattern",
    area: "v1.1 Builder Patterns",
    description: "Public content index/detail routes plus authenticated editorial dashboard and publishing workflow.",
    summary: "Use this for docs, blogs, directories, content hubs, and editorial sites.",
    keywords: ["cms", "content", "publishing", "articles", "editorial", "public", "rich-text"],
    sourcePath: "examples/v1.0/pattern-lightweight-cms.json",
    snippet: "stylyf validate --spec examples/v1.0/pattern-lightweight-cms.json",
    searchText: "cms content publishing articles editorial public rich text blog docs directory",
  },
  {
    id: "pattern-public-utility-saved-results",
    label: "Public Utility With Saved Results",
    kind: "pattern",
    area: "v1.1 Builder Patterns",
    description: "Marketing/tool surfaces for a free utility plus authenticated saved-result history.",
    summary: "Use this for calculators, analyzers, converters, generators, and lightweight lead-magnet tools.",
    keywords: ["utility", "tool", "saved-results", "calculator", "converter", "analyzer", "public"],
    sourcePath: "examples/v1.0/pattern-public-utility-saved-results.json",
    snippet: "stylyf validate --spec examples/v1.0/pattern-public-utility-saved-results.json",
    searchText: "utility tool saved results calculator converter analyzer generator public",
  },
];
